conky.config = {
    own_window = true,
    own_window_type = 'desktop',
    own_window_transparent = true,

    alignment = 'top_right',

    gap_x = 25,
    gap_y = 80,

    minimum_width = 240,

    use_xft = true,
    font = 'Sans:size=11',

    default_color = 'white',

    update_interval = 2,

    double_buffer = true,

    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
};

conky.text = [[
${font Sans:bold:size=15}CloudStation${font}

${color1}Region${color}  ${execi 300 curl -s -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/region | awk -F/ '{print $NF}'}

${color1}Age${color}     ${uptime_short}

${color1}CPU${color}     ${cpubar 6,90} ${cpu}%
${color1}RAM${color}     ${membar 6,90} ${memperc}%
]];
